=== sivaku-debug/BasicPrograms_WT/CSE_iii_i/WebContent/WEB-INF/emp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT emps (emp+) > 
<!ELEMENT emp (id,name,sal,dept,company)> 
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT sal (#PCDATA)> 
<!ELEMENT dept (#PCDATA)> 
<!ELEMENT company (#PCDATA)> 
<!ATTLIST dept grade CDATA #REQUIRED 
block CDATA "A"> 
<!ATTLIST id prefix CDATA #IMPLIED> 
<!ENTITY addr "Infosys Technoligies,Gachibowli,Hyderabad">

=== sivaku-debug/BasicPrograms_WT/CSE_iii_i/WebContent/WEB-INF/Empvalidate.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?> 

<!DOCTYPE emps SYSTEM "emp.dtd"> 
<emps> 
<emp> 
<id prefix="INF">101</id> 
<name>Ramesh</name> 
<sal>85900</sal> 
<dept grade="B"> Developer</dept> 
<company>&addr;</company> 
</emp> 
<emp> 
<id>121</id> 
<name>Suresh</name> 
<sal>65900</sal> 
<dept grade="C"> Tester</dept> 
<company>&addr;</company> 
</emp> 
<emp> 
<id>131</id> 
<name>Ganesh</name> 
<sal>185900</sal> 
<dept grade="A">Designer</dept> 
<company>&addr;</company> 
</emp> 
</emps>
